### ISSUE TITLE
Shuffle all songs

### ISSUE THREAD

**Issue by nikolowry** [MediaBrowser/MediaBrowser.Roku#152]
Switched from Plex about a week ago, and my only disappointment thus far is how complicated it is to shuffle through my entire Music Library. I could always make a playlist from the Web UI running on my Emby Server which encompasses every song, but that isn't a practical solution.  Am I overlooking something? Suggestions appreciated.

I also might open an issue with Emby Server requesting support for importing .m3u files as playlists -- I have a bash script that runs whenever my ~/Music folder changes and it creates a .m3u playlist 'all', that's how I get around this problem with mpd/ncmcpp.

**Comment by LukePulverenti** [comment]
Hi, thanks for the feedback. We are actively working on adding this to all of our apps, so you'll begin to see it in the next set of releases. Every list screen will have play all & shuffle buttons.
